// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc1SjwS4W-7iqipNCw9yDZ6yE0GAsj6Gw',
    appId: '1:127040816700:web:4d8ac06dc0866857482539',
    messagingSenderId: '127040816700',
    projectId: 'nesba-5a3fb',
    authDomain: 'nesba-5a3fb.firebaseapp.com',
    storageBucket: 'nesba-5a3fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMDae6_fp8T4cZjD7AKN8vinfLmblHzdo',
    appId: '1:127040816700:android:053ebc5c5c312cd0482539',
    messagingSenderId: '127040816700',
    projectId: 'nesba-5a3fb',
    storageBucket: 'nesba-5a3fb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuAippOGNJBqRZqAN9fmRXjk_NLHJjHjo',
    appId: '1:127040816700:ios:e7b3d0acd2546f22482539',
    messagingSenderId: '127040816700',
    projectId: 'nesba-5a3fb',
    storageBucket: 'nesba-5a3fb.firebasestorage.app',
    iosBundleId: 'com.example.nesba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBc1SjwS4W-7iqipNCw9yDZ6yE0GAsj6Gw',
    appId: '1:127040816700:web:36dae56030ccc716482539',
    messagingSenderId: '127040816700',
    projectId: 'nesba-5a3fb',
    authDomain: 'nesba-5a3fb.firebaseapp.com',
    storageBucket: 'nesba-5a3fb.firebasestorage.app',
  );
}
